#This is an example of writing text to an excel sheet to be read by the quiz script, can be used for bot integration later
import pandas as pd

# Create a DataFrame with the US states and capitals
data = {
    'Question': [
        'What is the capital of Alabama?',
        'What is the capital of Alaska?',
        'What is the capital of Arizona?',
        'What is the capital of Arkansas?',
        'What is the capital of California?',
        'What is the capital of Colorado?',
        'What is the capital of Connecticut?',
        'What is the capital of Delaware?',
        'What is the capital of Florida?',
        'What is the capital of Georgia?',
        'What is the capital of Hawaii?',
        'What is the capital of Idaho?',
        'What is the capital of Illinois?',
        'What is the capital of Indiana?',
        'What is the capital of Iowa?',
        'What is the capital of Kansas?',
        'What is the capital of Kentucky?',
        'What is the capital of Louisiana?',
        'What is the capital of Maine?',
        'What is the capital of Maryland?',
        'What is the capital of Massachusetts?',
        'What is the capital of Michigan?',
        'What is the capital of Minnesota?',
        'What is the capital of Mississippi?',
        'What is the capital of Missouri?',
        'What is the capital of Montana?',
        'What is the capital of Nebraska?',
        'What is the capital of Nevada?',
        'What is the capital of New Hampshire?',
        'What is the capital of New Jersey?',
        'What is the capital of New Mexico?',
        'What is the capital of New York?',
        'What is the capital of North Carolina?',
        'What is the capital of North Dakota?',
        'What is the capital of Ohio?',
        'What is the capital of Oklahoma?',
        'What is the capital of Oregon?',
        'What is the capital of Pennsylvania?',
        'What is the capital of Rhode Island?',
        'What is the capital of South Carolina?',
        'What is the capital of South Dakota?',
        'What is the capital of Tennessee?',
        'What is the capital of Texas?',
        'What is the capital of Utah?',
        'What is the capital of Vermont?',
        'What is the capital of Virginia?',
        'What is the capital of Washington?',
        'What is the capital of West Virginia?',
        'What is the capital of Wisconsin?',
        'What is the capital of Wyoming?'
    ],
    'Answer': [
        'Montgomery',
        'Juneau',
        'Phoenix',
        'Little Rock',
        'Sacramento',
        'Denver',
        'Hartford',
        'Dover',
        'Tallahassee',
        'Atlanta',
        'Honolulu',
        'Boise',
        'Springfield',
        'Indianapolis',
        'Des Moines',
        'Topeka',
        'Frankfort',
        'Baton Rouge',
        'Augusta',
        'Annapolis',
        'Boston',
        'Lansing',
        'St. Paul',
        'Jackson',
        'Jefferson City',
        'Helena',
        'Lincoln',
        'Carson City',
        'Concord',
        'Trenton',
        'Santa Fe',
        'Albany',
        'Raleigh',
        'Bismarck',
        'Columbus',
        'Oklahoma City',
        'Salem',
        'Harrisburg',
        'Providence',
        'Columbia',
        'Pierre',
        'Nashville',
        'Austin',
        'Salt Lake City',
        'Montpelier',
        'Richmond',
        'Olympia',
        'Charleston',
        'Madison',
        'Cheyenne'
    ]
}

df = pd.DataFrame(data)

# Export the DataFrame to an Excel file
df.to_excel('excel/quiz_uscapitals.xlsx', index=False)
